# Generated by Django 2.0.2 on 2020-04-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, db_column='Patient_ID', max_length=255, null=True)),
                ('chartno', models.CharField(blank=True, db_column='ChartNo', max_length=255, null=True)),
                ('admissiondate', models.CharField(blank=True, db_column='AdmissionDate', max_length=255, null=True)),
                ('erdate', models.CharField(blank=True, db_column='ERDate', max_length=255, null=True)),
                ('notetype', models.CharField(blank=True, db_column='NoteType', max_length=255, null=True)),
                ('datetime', models.CharField(blank=True, db_column='DateTime', max_length=255, null=True)),
                ('serial', models.IntegerField(blank=True, db_column='Serial', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'test_emr',
                'managed': True,
            },
        ),
    ]
