# Generated by Django 2.0.2 on 2020-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
