# Generated by Django 3.0.2 on 2020-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmrCui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emrid', models.CharField(blank=True, db_column='EmrId', max_length=50, null=True)),
                ('cuilist', models.CharField(blank=True, db_column='CuiList', max_length=20000, null=True)),
            ],
            options={
                'db_table': 'emr_cui',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrCuiWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emrid', models.CharField(blank=True, db_column='EmrId', max_length=50, null=True)),
                ('cui', models.CharField(blank=True, db_column='Cui', max_length=10, null=True)),
                ('wordlist', models.CharField(blank=True, db_column='WordList', max_length=20000, null=True)),
            ],
            options={
                'db_table': 'emr_cui_word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emrid', models.CharField(db_column='EmrId', max_length=50)),
                ('sequence', models.IntegerField(db_column='Sequence')),
                ('emrcontent', models.CharField(db_column='EmrContent', max_length=5000)),
            ],
            options={
                'db_table': 'emr_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalizedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=100)),
                ('emrid_id', models.CharField(db_column='EmrId_id', max_length=50)),
                ('dep_id_id', models.CharField(max_length=100)),
                ('doctor_id_id', models.CharField(max_length=100)),
                ('patient_id_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hospitalized_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutpatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=100)),
                ('emrid_id', models.CharField(db_column='EmrId_id', max_length=50)),
                ('dep_id_id', models.CharField(max_length=100)),
                ('doctor_id_id', models.CharField(max_length=100)),
                ('patient_id_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'outpatient_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TestEmr',
        ),
    ]
