# Generated by Django 2.0.2 on 2020-04-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_auto_20200418_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='testemr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
