# Generated by Django 2.0.2 on 2020-04-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_auto_20200418_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testemr',
            options={'managed': True},
        ),
    ]
