# Generated by Django 2.0.2 on 2020-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpr_data',
            name='login_user',
        ),
        migrations.AddField(
            model_name='tpr_data',
            name='doctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tpr_data',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
