# Generated by Django 2.0.2 on 2020-05-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalized_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('EmrId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Emr_data', to_field='EmrId')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitalized_doctor', to='db_models.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitalized_patients', to='db_models.Patient', to_field='patient_id')),
            ],
        ),
        migrations.CreateModel(
            name='OutPatient_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('EmrId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Emr_data', to_field='EmrId')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outpatient_doctor', to='db_models.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outpatient_patients', to='db_models.Patient', to_field='patient_id')),
            ],
        ),
    ]
