# Generated by Django 2.0.2 on 2020-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpr_data',
            name='create_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tpr_data',
            name='create_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
