# Generated by Django 2.0.2 on 2020-05-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20200506_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation_form',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dep_evaluation', to='db_models.Department'),
        ),
    ]
