# Generated by Django 2.0.2 on 2020-04-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20200418_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpr_data',
            name='doctor',
        ),
    ]
