# Generated by Django 2.0.2 on 2020-05-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_auto_20200506_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='begin_at',
        ),
        migrations.RemoveField(
            model_name='med',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='med',
            name='routePmName',
        ),
        migrations.AddField(
            model_name='med',
            name='EncounterId',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med',
            name='exeDt',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med',
            name='patient_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Patient', to_field='patient_id'),
            preserve_default=False,
        ),
    ]
