# Generated by Django 2.0.2 on 2020-05-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_auto_20200510_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emr_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmrId', models.CharField(max_length=50)),
                ('Sequence', models.IntegerField()),
                ('EmrContent', models.CharField(max_length=1000)),
            ],
        ),
    ]
