# Generated by Django 2.0.2 on 2020-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_emr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emr_data',
            name='EmrContent',
            field=models.CharField(max_length=5000),
        ),
    ]
