# Generated by Django 3.0.2 on 2020-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mri_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'xray_data',
                'managed': False,
            },
        ),
    ]
