# Generated by Django 2.0.2 on 2020-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200315_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='department',
            field=models.CharField(choices=[('dept1', 'dept1'), ('dept2', 'dept2'), ('dept3', 'dept3')], max_length=100),
        ),
    ]
