# Generated by Django 2.0.2 on 2020-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TprData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('patient_id_id', models.CharField(max_length=100)),
                ('resident_doctor_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tpr_data',
                'managed': False,
            },
        ),
    ]
