# Generated by Django 2.0.2 on 2020-03-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpr_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_no', models.IntegerField(max_length=20)),
                ('BT_TA', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('HR', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('RR', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('DBP', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('SBP', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('cre_dt', models.IntegerField(max_length=7)),
                ('cre_ti', models.IntegerField(max_length=6)),
            ],
        ),
    ]
