# Generated by Django 2.0.2 on 2020-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_patient_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpr_process',
            name='cre_dt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tpr_process',
            name='cre_ti',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tpr_process',
            name='pat_no',
            field=models.IntegerField(),
        ),
    ]
