# Generated by Django 2.0.2 on 2020-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_patient_detail', '0002_auto_20200405_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tpr_process',
        ),
    ]
