# Generated by Django 2.0.2 on 2020-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('division', models.CharField(max_length=50)),
                ('doctors_name', models.CharField(max_length=20)),
                ('patients_name', models.CharField(max_length=20)),
            ],
        ),
    ]
