# Generated by Django 2.0.2 on 2020-03-11 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 22, 17, 36, 902718)),
        ),
    ]
