# Generated by Django 2.0.2 on 2020-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_patient', '0002_auto_20200311_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient_data',
        ),
    ]
