# Generated by Django 3.0.2 on 2020-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('select_patient', '0003_delete_patient_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=6000)),
                ('doctor_id_id', models.CharField(max_length=100)),
                ('patient_id_id', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'memo_data',
                'managed': False,
            },
        ),
    ]
